### ISSUE TITLE
cant upload big files

### ISSUE THREAD

**Issue by TomerGamerTV** [FarisCode511/BlackUpload#3]
im getting its error after trying to upload big files:

Warning: count(): Parameter must be an array or an object that implements Countable in /home/vol1_1/epizy.com/epiz_26442241/htdocs/classes/Upload.php on line 707

Warning: array_keys() expects parameter 1 to be array, null given in /home/vol1_1/epizy.com/epiz_26442241/htdocs/classes/Upload.php on line 708

here is my site: [https://ultracloudupload.xyz/](url)

**Comment by FarisCode511** [comment]
It's an issue that I couldn't get rid of it

the upload limit is 100MB anything more than that the code will break

Sometimes it breaks on 50MB

If you want to make a cloud service I recommend you try OwnCloud

**Comment by TomerGamerTV** [comment]
you have any free or cheap hosting service? infinityfree not allowing it

plus the thing that I did not working
