### ISSUE TITLE
getting errors after uploading upload.sql

### ISSUE THREAD

**Issue by TomerGamerTV** [FarisCode511/BlackUpload#4]
Warning in ./libraries/classes/Dbi/DbiMysqli.php#213
 mysqli_query(): MySQL server has gone away

Backtrace

./libraries/classes/Dbi/DbiMysqli.php#213: mysqli_query(
,
string 'SELECT `SCHEMA_NAME` FROM `INFORMATION_SCHEMA`.`SCHEMATA`, (SELECT DB_first_level FROM ( SELECT DISTINCT SUBSTRING_INDEX(SCHEMA_NAME, \'_\', 1) DB_first_level FROM INFORMATION_SCHEMA.SCHEMATA WHERE TRUE ) t ORDER BY DB_first_level ASC LIMIT 0, 100) t2 WHERE TRUE AND 1 = LOCATE(CONCAT(DB_first_level, \'_\'), CONCAT(SCHEMA_NAME, \'_\')) ORDER BY SCHEMA_NAME ASC',
integer 0,
)
./libraries/classes/DatabaseInterface.php#319: PhpMyAdmin\Dbi\DbiMysqli->realQuery(
string 'SELECT `SCHEMA_NAME` FROM `INFORMATION_SCHEMA`.`SCHEMATA`, (SELECT DB_first_level FROM ( SELECT DISTINCT SUBSTRING_INDEX(SCHEMA_NAME, \'_\', 1) DB_first_level FROM INFORMATION_SCHEMA.SCHEMATA WHERE TRUE ) t ORDER BY DB_first_level ASC LIMIT 0, 100) t2 WHERE TRUE AND 1 = LOCATE(CONCAT(DB_first_level, \'_\'), CONCAT(SCHEMA_NAME, \'_\')) ORDER BY SCHEMA_NAME ASC',
,
integer 0,
)
./libraries/classes/DatabaseInterface.php#1782: PhpMyAdmin\DatabaseInterface->tryQuery(
string 'SELECT `SCHEMA_NAME` FROM `INFORMATION_SCHEMA`.`SCHEMATA`, (SELECT DB_first_level FROM ( SELECT DISTINCT SUBSTRING_INDEX(SCHEMA_NAME, \'_\', 1) DB_first_level FROM INFORMATION_SCHEMA.SCHEMATA WHERE TRUE ) t ORDER BY DB_first_level ASC LIMIT 0, 100) t2 WHERE TRUE AND 1 = LOCATE(CONCAT(DB_first_level, \'_\'), CONCAT(SCHEMA_NAME, \'_\')) ORDER BY SCHEMA_NAME ASC',
integer 256,
integer 0,
boolean false,
)
./libraries/classes/Navigation/Nodes/Node.php#459: PhpMyAdmin\DatabaseInterface->fetchResult(string 'SELECT `SCHEMA_NAME` FROM `INFORMATION_SCHEMA`.`SCHEMATA`, (SELECT DB_first_level FROM ( SELECT DISTINCT SUBSTRING_INDEX(SCHEMA_NAME, \'_\', 1) DB_first_level FROM INFORMATION_SCHEMA.SCHEMATA WHERE TRUE ) t ORDER BY DB_first_level ASC LIMIT 0, 100) t2 WHERE TRUE AND 1 = LOCATE(CONCAT(DB_first_level, \'_\'), CONCAT(SCHEMA_NAME, \'_\')) ORDER BY SCHEMA_NAME ASC')
./libraries/classes/Navigation/NavigationTree.php#290: PhpMyAdmin\Navigation\Nodes\Node->getData(
string 'databases',
string '0',
string '',
)
./libraries/classes/Navigation/NavigationTree.php#849: PhpMyAdmin\Navigation\NavigationTree->_buildPath()
./libraries/classes/Navigation/Navigation.php#59: PhpMyAdmin\Navigation\NavigationTree->renderState()
./libraries/classes/Header.php#440: PhpMyAdmin\Navigation\Navigation->getDisplay()
./libraries/classes/Response.php#266: PhpMyAdmin\Header->getDisplay()
./libraries/classes/Response.php#279: PhpMyAdmin\Response->_getDisplay()
./libraries/classes/Response.php#438: PhpMyAdmin\Response->_htmlResponse()
PhpMyAdmin\Response->response()

----------------------and getting it-----------------------------
Warning in ./libraries/classes/Dbi/DbiMysqli.php#213
 mysqli_query(): Error reading result set's header

Backtrace

./libraries/classes/Dbi/DbiMysqli.php#213: mysqli_query(
,
string 'SELECT `SCHEMA_NAME` FROM `INFORMATION_SCHEMA`.`SCHEMATA`, (SELECT DB_first_level FROM ( SELECT DISTINCT SUBSTRING_INDEX(SCHEMA_NAME, \'_\', 1) DB_first_level FROM INFORMATION_SCHEMA.SCHEMATA WHERE TRUE ) t ORDER BY DB_first_level ASC LIMIT 0, 100) t2 WHERE TRUE AND 1 = LOCATE(CONCAT(DB_first_level, \'_\'), CONCAT(SCHEMA_NAME, \'_\')) ORDER BY SCHEMA_NAME ASC',
integer 0,
)
./libraries/classes/DatabaseInterface.php#319: PhpMyAdmin\Dbi\DbiMysqli->realQuery(
string 'SELECT `SCHEMA_NAME` FROM `INFORMATION_SCHEMA`.`SCHEMATA`, (SELECT DB_first_level FROM ( SELECT DISTINCT SUBSTRING_INDEX(SCHEMA_NAME, \'_\', 1) DB_first_level FROM INFORMATION_SCHEMA.SCHEMATA WHERE TRUE ) t ORDER BY DB_first_level ASC LIMIT 0, 100) t2 WHERE TRUE AND 1 = LOCATE(CONCAT(DB_first_level, \'_\'), CONCAT(SCHEMA_NAME, \'_\')) ORDER BY SCHEMA_NAME ASC',
,
integer 0,
)
./libraries/classes/DatabaseInterface.php#1782: PhpMyAdmin\DatabaseInterface->tryQuery(
string 'SELECT `SCHEMA_NAME` FROM `INFORMATION_SCHEMA`.`SCHEMATA`, (SELECT DB_first_level FROM ( SELECT DISTINCT SUBSTRING_INDEX(SCHEMA_NAME, \'_\', 1) DB_first_level FROM INFORMATION_SCHEMA.SCHEMATA WHERE TRUE ) t ORDER BY DB_first_level ASC LIMIT 0, 100) t2 WHERE TRUE AND 1 = LOCATE(CONCAT(DB_first_level, \'_\'), CONCAT(SCHEMA_NAME, \'_\')) ORDER BY SCHEMA_NAME ASC',
integer 256,
integer 0,
boolean false,
)
./libraries/classes/Navigation/Nodes/Node.php#459: PhpMyAdmin\DatabaseInterface->fetchResult(string 'SELECT `SCHEMA_NAME` FROM `INFORMATION_SCHEMA`.`SCHEMATA`, (SELECT DB_first_level FROM ( SELECT DISTINCT SUBSTRING_INDEX(SCHEMA_NAME, \'_\', 1) DB_first_level FROM INFORMATION_SCHEMA.SCHEMATA WHERE TRUE ) t ORDER BY DB_first_level ASC LIMIT 0, 100) t2 WHERE TRUE AND 1 = LOCATE(CONCAT(DB_first_level, \'_\'), CONCAT(SCHEMA_NAME, \'_\')) ORDER BY SCHEMA_NAME ASC')
./libraries/classes/Navigation/NavigationTree.php#290: PhpMyAdmin\Navigation\Nodes\Node->getData(
string 'databases',
string '0',
string '',
)
./libraries/classes/Navigation/NavigationTree.php#849: PhpMyAdmin\Navigation\NavigationTree->_buildPath()
./libraries/classes/Navigation/Navigation.php#59: PhpMyAdmin\Navigation\NavigationTree->renderState()
./libraries/classes/Header.php#440: PhpMyAdmin\Navigation\Navigation->getDisplay()
./libraries/classes/Response.php#266: PhpMyAdmin\Header->getDisplay()
./libraries/classes/Response.php#279: PhpMyAdmin\Response->_getDisplay()
./libraries/classes/Response.php#438: PhpMyAdmin\Response->_htmlResponse()
PhpMyAdmin\Response->response()

**Comment by FarisCode511** [comment]
this is an invalid issue

because it is an issue with your hosting, not the software
